SCMOD-7632: removed the logging of log4j and commons-logging
JobService/job-service pull request #119
Opened 2019-10-16 13:23 UTC by gaana-vishwnath

2019-10-18 14:28 UTC, gaana-vishwnath commented
This needs a change in the liquibase-installer version before the final merge

2019-10-24 00:38 UTC, dermot-hardy requested changes

2019-10-24 00:38 UTC, dermot-hardy commented on pom.xml
> +                <version>1.17.0-SCMOD-7632-GV-SNAPSHOT</version>
Don't forget to revert before merging.

2019-10-24 00:38 UTC, dermot-hardy commented on pom.xml
> +                <version>1.0.0-SNAPSHOT</version>
This has now been released (and the coordinates have changed slightly).

2019-10-24 00:38 UTC, dermot-hardy commented on worker-jobtracking-container/worker.sh
> +    echo "$@" | $(dirname "$0")/../scripts/caf-log-format.sh "${0##*/}"
Second argument missing `$$`

2019-10-24 00:38 UTC, dermot-hardy commented on job-service-scheduled-executor-container/worker.sh
> +    echo "$@" | $(dirname "$0")/../scripts/caf-log-format.sh "${0##*/}"
Second argument missing `$$`

2019-10-24 00:38 UTC, dermot-hardy commented on job-service-postgres-container/pom.xml
> +        <dependency>
Whitespace at end of line.

2019-10-24 00:38 UTC, dermot-hardy commented on job-service-postgres-container/pom.xml
> +        </dependency>
I can't see why these two are needed here.  Aren't they already in the uber-jar?

2019-10-24 00:38 UTC, dermot-hardy commented on job-service-container/pom.xml
> +        <dependency>
Whitespace at end of line

2019-10-24 00:38 UTC, dermot-hardy commented on job-service-container/pom.xml
> +        <!-- End Logging -->
I don't think these two should be here, given that this is packaging war files and uber jars.  Did you add them for tests?  If so then they should be test scope.

2019-10-24 00:38 UTC, dermot-hardy commented on job-service-container/pom.xml
> +                                            </dependencySet>
What is the purpose of this new dependency set?

2019-10-24 00:38 UTC, dermot-hardy commented on job-service-config/pom.xml
> +            </exclusions>
Exclusions should be in dependency management in the aggregator.

2019-11-01 11:37 UTC, gaana-vishwnath commented
closing this request as a different branches with the changes has been done and merged

2019-11-01 11:37 UTC, closed without merging