SCMOD-5777: Set database connection application name
JobService/job-service pull request #124
Opened 2020-01-15 16:06 UTC by thilagasanthosh

http://sou-jenkins2.swinfra.net/job/JobService/view/Developer/job/JobService~job-service~SCMOD-5777-New~CI
![JobService](https://user-images.githubusercontent.com/5318352/72449637-e725b000-37b0-11ea-803e-7633959ce5a2.PNG)
![jobtracking-worker](https://user-images.githubusercontent.com/5318352/72449646-ea20a080-37b0-11ea-82b1-4314cd59ab1d.PNG)
![ScheduledExecutor](https://user-images.githubusercontent.com/5318352/72449652-ee4cbe00-37b0-11ea-830f-7ae257acfeea.PNG)

The screenshots were taken while running containers in debug mode.

2020-01-15 19:51 UTC, dermot-hardy requested changes
Why aren't you following the convention used by pre-existing environment variables?

2020-01-16 13:48 UTC, thilagasanthosh commented
The CAF_APPNAME is not a new variable and was existing before. Do this to be changed to a different one? If so, Is CAF_JOB_SERVICE_APP_NAME ok for a variable name?

2020-01-16 13:58 UTC, dermot-hardy commented
The `CAF_APPNAME` that is currently used is nothing to do with the database connection.  Choose the environment variable names based on what is consistent.

2020-01-17 13:45 UTC, thilagasanthosh commented
@dermot-hardy ,
The Variable name is changed as expected. Could you look at this PR?

2020-01-17 14:06 UTC, dermot-hardy requested changes

2020-01-17 14:06 UTC, dermot-hardy commented on deploy/src/main/resources-filtered/jobservice-deployment.yaml
> +          - name: CAF_DATABASE_APP_NAME
`CAF_DATABASE_APPNAME`

2020-01-17 14:06 UTC, dermot-hardy commented on job-service/src/test/java/com/hpe/caf/services/job/api/JobsPutTest.java
> +        newEnv.put("CAF_DATABASE_APP_NAME","testAppName");
`CAF_DATABASE_APPNAME`

2020-01-17 14:06 UTC, dermot-hardy commented on job-service-scheduled-executor/src/main/java/com/hpe/caf/services/job/scheduled/executor/ScheduledExecutorConfig.java
> +    }
Put this with the other database property accessors.

2020-01-17 14:06 UTC, dermot-hardy commented on worker-jobtracking/src/main/java/com/hpe/caf/worker/jobtracking/JobTrackingWorkerReporter.java
> +		this.appName = Objects.requireNonNull(JobDatabaseProperties.getApplicationName());
- Alignment
- App Name should be optional.  Otherwise this would be a breaking change.

2020-01-17 14:35 UTC, dermot-hardy approved these changes

2020-01-17 14:35 UTC, merged