SCMOD-13865: Remove propagate_failures
JobService/job-service pull request #253
Opened 2021-06-09 11:48 UTC by xbreizh

https://portal.digitalsafe.net/browse/SCMOD-13865

2021-06-09 11:50 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=JobService&REPO_NAME=job-service&BRANCH_NAME=SCMOD-13865) to go ahead and create the build...

2021-06-09 11:53 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/JobService/job/JobService~job-service~SCMOD-13865~CI

2021-06-09 12:33 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/JobService_CI_job-service_SCMOD-13865

2021-06-11 12:54 UTC, dermot-hardy approved these changes

2021-06-11 12:56 UTC, dermot-hardy requested changes

2021-06-11 12:56 UTC, dermot-hardy commented on pom.xml
> +    <version>5.0.0-SNAPSHOT</version>
What about all the other pom files?

2021-06-11 13:07 UTC, xbreizh commented on pom.xml
> +    <version>5.0.0-SNAPSHOT</version>
Done

2021-06-11 18:48 UTC, merged