SCMOD-15074 Job Service: Cancellation of complex jobs can fail
JobService/job-service pull request #270
Opened 2021-10-01 07:01 UTC by simranjeetc

https://portal.digitalsafe.net/browse/SCMOD-15074

2021-10-01 11:55 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/JobService/job/JobService~job-service~SCMOD-15074~CI

2021-10-05 08:12 UTC, simranjeetc commented on job-service-container/pom.xml
> +                <task.table.deletion.count>10000</task.table.deletion.count>
This number now corresponds to number of parent tables. For every parent table, we are creating 20 twenty tables(child + parent). So approximately 10k * 20 tables are getting created in total.

2021-10-11 02:58 UTC, dermot-hardy requested changes

2021-10-11 02:58 UTC, dermot-hardy commented on job-service-container/src/test/java/com/hpe/caf/services/job/api/JobServiceIT.java
> +        connectionString = "http://127.0.0.1:25080/job-service/v1";
Is this meant to be changing?

2021-10-11 02:58 UTC, dermot-hardy commented on job-service-container/src/test/java/com/hpe/caf/services/job/api/JobServiceIT.java
> +
Pointless whitespace change

2021-10-11 02:58 UTC, dermot-hardy commented on job-service-container/src/test/java/com/hpe/caf/services/job/api/JobServiceIT.java
> +
Pointless whitespace change

2021-10-11 02:58 UTC, dermot-hardy commented on job-service-container/src/test/java/com/hpe/caf/services/job/api/JobServiceIT.java
> +        rabbitConfiguration.getRabbitConfiguration().setRabbitPort(Integer.parseInt("5672"));
Halting review... PR clearly not prepared for it.

2021-10-18 03:06 UTC, dermot-hardy requested changes

2021-10-18 03:06 UTC, dermot-hardy commented on job-service-db/src/main/resources/v5.0.0/changelog.xml
> +            <column name="table_name" type="VARCHAR(80)">
Why is this 80 rather than 63 like the `delete_log`?

2021-10-18 03:06 UTC, dermot-hardy commented on job-service-db/src/main/resources/procedures/dropDeletedTaskTables.sql
> +                END LOOP;
Did you mean to put the commit after the end loop?

2021-10-18 03:06 UTC, dermot-hardy commented on job-service-db/src/main/resources/procedures/dropDeletedTaskTables.sql
> +        END LOOP;
Pull the whole loop block in 4 spaces and pull the inner loop in 8 spaces so you're using the same spacing convention that is already used in this file.  When in Rome...

2021-10-18 03:06 UTC, dermot-hardy commented on job-service-db/src/main/resources/procedures/populateDeleteLogTable.sql
> +CREATE OR REPLACE PROCEDURE populate_delete_log_table(
Prefix procedure name with `internal_`, in line with the convention in this project for identifying routines not intended to be called directly by the code.

2021-10-18 03:06 UTC, dermot-hardy commented on job-service-db/src/main/resources/procedures/populateDeleteLogTable.sql
> +    in_task_id VARCHAR(70),
- As far as I can see you're actually passing in the task table name here - rename parameter to `in_task_table_name`.
- I think this should be `VARCHAR(63)`.

2021-10-18 03:06 UTC, dermot-hardy commented on job-service-db/src/main/resources/procedures/populateDeleteLogTable.sql
> +                END IF;
Do we really need any of this `query_count` stuff?  Isn't the fact that you've changed the recursion from functions to procedures enough to ensure that the select statements are not in the same transaction?

2021-10-19 11:33 UTC, simranjeetc commented on job-service-db/src/main/resources/procedures/populateDeleteLogTable.sql
> +                END IF;
I am not sure if we need to accommodate the scenario where the recursion for one parent task table can result in doing a select on ~15k child(sub-child and so on) tables. If that is a valid scenario then query_count based commit is required otherwise I can get rid of it. This would essentially mean getting rid of the commit statement present at line 47. 

Stored procedures by itself do not provide a transaction boundary but rather provide the ability to use transaction ending statements like `COMMIT`, `ROLLBACK` etc. `BEGIN` and `END` do not serve as transaction boundary in postgres either. Actually, if we remove the commit on line 47, we can choose to change this stored procedure to a function. This would still work because of the presence of [this commit statement](https://github.com/JobService/job-service/blob/118009a2295fc118484d3635f38ca2c819b785cf/job-service-db/src/main/resources/procedures/dropDeletedTaskTables.sql#L47). Of-course that would need to satisfy the above mentioned condition of not doing a select on more than ~15k tables(child + sub-child + ...).

2021-10-19 11:46 UTC, simranjeetc commented on job-service-db/src/main/resources/procedures/dropDeletedTaskTables.sql
> +                END LOOP;
This can indeed be moved after the `END LOOP`. It would depend on the what we do [here](https://github.com/JobService/job-service/pull/270/files#r731768604). Because, if we remove [this commit statement ](https://github.com/JobService/job-service/blob/118009a2295fc118484d3635f38ca2c819b785cf/job-service-db/src/main/resources/procedures/populateDeleteLogTable.sql#L47) and move [this](https://github.com/JobService/job-service/blob/118009a2295fc118484d3635f38ca2c819b785cf/job-service-db/src/main/resources/procedures/dropDeletedTaskTables.sql#L47) after the `END LOOP`, then we should be ok with the scenario where iterating over 10(commit_limit) parent tables + child tables + .. goes over 15k table count collectively. 

If we keep [this commit statement](https://github.com/JobService/job-service/blob/118009a2295fc118484d3635f38ca2c819b785cf/job-service-db/src/main/resources/procedures/populateDeleteLogTable.sql#L47), then this can be moved out without much concern of running into max transactions error.

2021-10-19 23:35 UTC, dermot-hardy commented on job-service-db/src/main/resources/procedures/populateDeleteLogTable.sql
> +                END IF;
> I am not sure if we need to accommodate the scenario where the recursion for one parent task table can result in doing a select on ~15k child(sub-child and so on) tables. If that is a valid scenario...

I would assume that we do need to accommodate that scenario and that it is valid.

> Stored procedures by itself do not provide a transaction boundary but rather provide the ability to use transaction

Ok, it's the unbalanced nature of it that I'm wary of but yes that answers this query.

2021-10-19 23:35 UTC, dermot-hardy commented on job-service-db/src/main/resources/procedures/populateDeleteLogTable.sql
> +    query_count INTEGER DEFAULT 0
I think the convention in this project is for parameters to be prefixed with `in_`.  (I must admit I hate that convention but when in Rome...)

2021-10-20 09:42 UTC, simranjeetc commented
@dermot-hardy Do you know why release builds not executing for this repo? http://sou-jenkins2.swinfra.net:8080/job/simranjeetc/job/simranjeetc~job-service~SCMOD-15074/17/console
![image](https://user-images.githubusercontent.com/4994904/138069467-612ab406-020a-41dd-8f62-e6501ab368bb.png)

2021-10-20 09:45 UTC, simranjeetc commented on job-service-container/pom.xml
> +                <task.table.deletion.count>10000</task.table.deletion.count>
With 10k parent table count, this would take ~20-25 mins to populate the data for this test in release build. Should I change this to a lower number say 3k parent tables which would result in creation of approx 60k tables overall?

2021-10-20 14:28 UTC, dermot-hardy commented
Set `SUSPENDED` to `FALSE` and try it again.

2021-10-20 14:30 UTC, dermot-hardy commented on job-service-container/pom.xml
> +                <task.table.deletion.count>10000</task.table.deletion.count>
Let's adjust it so that it is roughly the same amount of testing as before.

2021-10-20 14:36 UTC, dermot-hardy approved these changes

2021-10-20 14:36 UTC, dermot-hardy commented on job-service-container/src/test/java/com/hpe/caf/services/job/api/JobServiceIT.java
>      public void testDeleteLog() throws SQLException
Maybe we should test another level of depth.

2021-10-21 13:21 UTC, simranjeetc commented on job-service-container/src/test/java/com/hpe/caf/services/job/api/JobServiceIT.java
>      public void testDeleteLog() throws SQLException
Addressed in 990393e

2021-10-21 14:51 UTC, dermot-hardy approved these changes

2021-10-21 20:04 UTC, merged