CAF-2670: Changes to ensure jobs with no sub tasks are completed.
JobService/job-service pull request #32
Opened 2017-11-24 12:05 UTC by mulhollandc

Associated PRs for this work:
Worker-Framework: https://github.com/WorkerFramework/worker-framework/pull/60
Worker-Batch: https://github.com/JobService/worker-batch/pull/6
Worker-GlobFilter: https://github.com/JobService/worker-globfilter/pull/4

2017-11-24 14:18 UTC, glucy approved these changes

2017-11-27 20:01 UTC, dermot-hardy requested changes

2017-11-27 20:01 UTC, dermot-hardy commented on worker-jobtracking/src/main/java/com/hpe/caf/worker/jobtracking/JobTrackingWorkerFactory.java
> +            if (trackToPipe == null && (proxiedTaskMessage.getTo() != null)) {
I'd say drop this whole block - I don't see a reason to warn when `trackToPipe == null` regardless of whether `proxiedTaskMessage.getTo()` is `null` or not.

2017-11-28 14:17 UTC, mulhollandc commented
Hi @dermot-hardy Code review changes made.

2017-11-28 15:33 UTC, dermot-hardy approved these changes

2017-11-28 15:35 UTC, merged