633176: Ensure staging queue is declared when routing to staging queue
JobService/job-service pull request #332
Opened 2023-03-16 15:21 UTC by rorytorneymf

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=633176

Moving staging queue creation to before where `queueDeclarePassive` is called. Previously, `queueDeclarePassive` was being called on the original target queue rather than the staging queue. When a staging queue is deleted now, an error will be logged and the job retried, rather than the message being lost by being sent to a deleted queue.

2023-03-16 15:24 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=JobService&REPO_NAME=job-service&BRANCH_NAME=633176) to go ahead and create the build...

2023-03-16 15:26 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/JobService/job/JobService~job-service~633176~CI

2023-03-21 15:47 UTC, rorytorneymf commented on pom.xml
> +                <version>3.4.0-633176-SNAPSHOT</version>
Remove dev branch before merging

2023-03-21 15:47 UTC, rorytorneymf commented on pom.xml
> +                <version>1.0.0-633176-SNAPSHOT</version>
Remove dev branch before merging

2023-03-23 11:41 UTC, andyreidz requested changes
As discussed, let's remove ReturnListener

2023-03-23 11:41 UTC, andyreidz commented on job-service-scheduled-executor/src/main/java/com/hpe/caf/services/job/scheduled/executor/ExceptionThrowingReturnListener.java
> +        throw new RuntimeException(errorMessage);
Can you describe the behaviour here? What is catching this exception? When it's thrown, what happens?

2023-03-23 12:11 UTC, rorytorneymf commented on job-service-scheduled-executor/src/main/java/com/hpe/caf/services/job/scheduled/executor/DatabasePoller.java
> -            LOG.debug("Sending task data to the target queue {} ...", workerAction);
I removed this debug log as its essentially a duplicate of this log:

https://github.com/JobService/job-service/pull/332/files#diff-71727cc500796b7649ac435047b76c4b12f456408f532e53a037918ec9d6bdc6R119

2023-03-28 12:23 UTC, andyreidz approved these changes

2023-03-29 16:01 UTC, merged