US749207: Upgrade okio
JobService/job-service pull request #347
Opened 2023-08-09 10:38 UTC by jonny-mccoubrey

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=749207

2023-08-09 10:41 UTC, jonny-mccoubrey commented
Where is okio dependency being consumed?

2023-08-09 10:46 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=JobService&REPO_NAME=job-service&BRANCH_NAME=US749207) to go ahead and create the build...

2023-08-09 10:53 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/JobService/job/JobService~job-service~US749207~CI

2023-08-09 11:46 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/JobService_CI_job-service_US749207

2023-08-14 10:05 UTC, frankmccarry requested changes
I'm still seeing version 2.5 in use in some modules.

2023-09-06 12:55 UTC, frankmccarry approved these changes

2023-09-07 12:44 UTC, merged