US771133/US868107: Correctly return responses from new endpoints
JobService/job-service pull request #368
Opened 2023-12-22 11:22 UTC by jonny-mccoubrey

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=771133
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=868107

2023-12-22 11:24 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=JobService&REPO_NAME=job-service&BRANCH_NAME=US711133_fix) to go ahead and create the build...

2023-12-22 11:25 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/JobService/job/JobService~job-service~US711133_fix~CI

2023-12-22 11:44 UTC, michael-bryson commented on job-service/src/main/java/com/hpe/caf/services/job/api/generated/JobsApiServiceImpl.java
> +        return Response.ok().entity(String.format("Successfully cancelled %s jobs", successfulCancellations)).build();
```suggestion
        return Response.ok().entity(String.format("Successfully canceled %s jobs", successfulCancellations)).build();
```
This should be US spelling unfortunately

2023-12-22 12:06 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/JobService_CI_job-service_US711133_fix

2024-01-02 13:35 UTC, andyreidz requested changes
Apologies for not thinking about this in the first review, let's return the number of canceled or deleted jobs instead of a string, that way it will be easier for a caller to validate the response.

2024-01-02 14:48 UTC, jonny-mccoubrey commented
This PR was initially correcting the MIME type that the two new endpoints were returning.
Initially we were returning a String response so MIME type `text/plain` was being used.

However, when we decided to return Long response instead, `text/plain` caused an error. For the Long response, we choose MIME type application/json and it works as expected.

2024-01-02 14:50 UTC, jonny-mccoubrey commented
NOTE: Have requested review but will wait for CI build of final commit to pass before merging

2024-01-02 21:14 UTC, andyreidz approved these changes

2024-01-03 09:14 UTC, merged