SEPG Dependency update issue: Drop junit 4 dependency
JobService/job-service pull request #417
Opened 2024-06-07 13:46 UTC by raghavendran-gopalakrishnan

2024-06-07 13:50 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://sou-jenkins2.swinfra.net/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=JobService&REPO_NAME=job-service&BRANCH_NAME=removeJunit) to go ahead and create the build...

2024-06-07 13:52 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://sou-jenkins2.swinfra.net/job/JobService/job/JobService~job-service~removeJunit~CI

2024-06-07 14:11 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/JobService_CI_job-service_removeJunit

2024-06-07 21:52 UTC, dermot-hardy requested changes

2024-06-07 21:52 UTC, dermot-hardy commented on pom.xml
> -            </dependency>
Removing the entry from dependency management does not remove the dependency.  All it does is to remove our control over the version of the dependency that will be used.  It's not a fault in the dependency updating tool that it is adding this entry back in; the tool is effectively telling you that the dependency is not gone.

Looking at the project I can see that it is coming in as a transitive dependency of `json-simple`, which is referenced by the `job-service-acceptance-tests` project:

![image](https://github.com/JobService/job-service/assets/20627297/30672de1-9c9d-45be-8468-094061373803)

Incidentally I had thought that we were no longer using `json-simple` following the [`US915106`](https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=915106) changes that I made about a month ago.  Obviously I was relying on the dependency reports which are not reporting on the test usages.

2024-06-10 07:34 UTC, raghavendran-gopalakrishnan commented on pom.xml
> +                </exclusions>
I have added junit as exclusion for now in scope of this ticket. If this solves the dependency problem, can I raise a separate ticket to remove json-simple?

2024-06-10 12:54 UTC, dermot-hardy approved these changes

2024-06-10 12:56 UTC, merged