US921241: Add update job progress to scheduled executor
JobService/job-service pull request #480
Opened 2024-12-16 13:41 UTC by caoimhelynch

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=921241

2024-12-16 15:11 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://sou-jenkins2.swinfra.net/job/JobService/job/JobService~job-service~US921241~CI

2025-01-03 15:52 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://hmf.gitlab.otxlab.net//I_job-service_US921241

2025-01-06 18:36 UTC, dermot-hardy requested changes

2025-01-06 18:36 UTC, dermot-hardy commented on job-service-db/src/main/resources/db/migration/procedures/public/R__update_job_progress.sql
> +        ) distinct_tasks
The inner `SELECT` is not necessary:

```suggestion
        FROM completed_subtask_report
        GROUP BY partition_id, job_id
```

2025-01-06 18:36 UTC, dermot-hardy commented on job-service-db/src/main/resources/db/migration/procedures/public/R__update_job_progress.sql
> + *  Name: update_job_progress
Adjust filename to match others.

2025-01-06 18:36 UTC, dermot-hardy commented on job-service-db/src/main/resources/db/migration/procedures/public/R__update_job_progress.sql
> +    PERFORM internal_update_job_progress(tasks_to_update.partition_id, tasks_to_update.job_id)
We need to control the transaction here.  We want each job to be updated in its own transaction, even when multiple jobs are being updated.  So for example if 100 jobs are being updated I would like for there to be 100 transactions.  This function should be called once in each transaction.

2025-01-07 15:54 UTC, dermot-hardy requested changes

2025-01-07 15:54 UTC, dermot-hardy commented on job-service-scheduled-executor/src/main/java/com/github/jobservice/scheduledexecutor/ScheduledExecutor.java
> +                ScheduledExecutorConfig.getJobProgressUpdatePeriod(), TimeUnit.SECONDS);
Give this its own single thread scheduler rather than reusing the job dispatch one.  We may as well create a third one for the drop tables when we're in here since it shouldn't be reusing the job dispatch one either.

2025-01-07 15:56 UTC, dermot-hardy commented on job-service-scheduled-executor/src/main/java/com/github/jobservice/scheduledexecutor/ScheduledExecutor.java
> +        scheduler.scheduleWithFixedDelay(new UpdateJobProgress(100), 20,
I'm fine with the 20 being hard-coded since it is just an initial delay but we should make that 100 configurable.

2025-01-07 16:31 UTC, dermot-hardy commented on job-service-contract/src/main/resources/com/github/jobservice/contract/swagger.yaml
> +          - Waiting
From reading the ticket it seems like the expectation was that this parameter would be added to the `/jobStats/count` endpoint as well.  Was this just missed?  Can it be easily added or should we extract it to a separate ticket?

2025-01-07 16:55 UTC, dermot-hardy requested changes

2025-01-07 16:55 UTC, dermot-hardy commented on job-service-scheduled-executor/src/main/java/com/github/jobservice/scheduledexecutor/ScheduledExecutorConfig.java
> +        final String  period = getPropertyOrEnvVar("CAF_JOB_PROGRESS_UPDATE_SCHEDULER_PERIOD");
```suggestion
        final String period = getPropertyOrEnvVar("CAF_JOB_PROGRESS_UPDATE_SCHEDULER_PERIOD");
```

2025-01-07 16:55 UTC, dermot-hardy commented on job-service-scheduled-executor/src/main/java/com/github/jobservice/scheduledexecutor/ScheduledExecutorConfig.java
> +            return 60;
Let's make this much more aggressive - maybe every 2 seconds by default.

2025-01-07 16:55 UTC, dermot-hardy commented on job-service-db/src/main/resources/db/migration/procedures/public/R__updateJobProgress.sql
> +          AND j.job_id = rec.job_id
This `rec` is clearly a mistake.  It is concerning that this issue doesn't cause any tests to fail, since presumably it means that no jobs would complete.

2025-01-07 16:57 UTC, dermot-hardy commented on job-service-db/src/main/resources/db/migration/procedures/public/R__updateJobProgress.sql
> +        PERFORM internal_update_job_progress(rec.partition_id, rec.job_id);
```suggestion
        PERFORM internal_update_job_progress(task.partition_id, task.job_id);
```

2025-01-07 17:01 UTC, caoimhelynch commented on job-service-contract/src/main/resources/com/github/jobservice/contract/swagger.yaml
> +          - Waiting
This was missed but should be easy to add.

2025-01-08 19:36 UTC, dermot-hardy approved these changes

2025-01-08 19:36 UTC, dermot-hardy commented on job-service-scheduled-executor/src/main/java/com/github/jobservice/scheduledexecutor/ScheduledExecutorConfig.java
> +            return 2;
Put this back to 100.

2025-01-09 09:06 UTC, merged