SCMOD-3294 & 3295 Updated to the latest version of Dropwizard and resolved issue
JobService/job-service pull request #49
Opened 2018-05-29 21:31 UTC by morvinshah4

2018-05-29 23:49 UTC, dermot-hardy commented
Why are there two branches?  What is the difference between the [SCMOD-3294](https://github.com/JobService/job-service/tree/SCMOD-3294) branch and the [SCMOD-3294-js](https://github.com/JobService/job-service/tree/SCMOD-3294-js) branch?

2018-05-29 23:57 UTC, dermot-hardy commented
Looking at it the [SCMOD-3294](https://github.com/JobService/job-service/tree/SCMOD-3294) one seems to be behind the [SCMOD-3294-js](https://github.com/JobService/job-service/tree/SCMOD-3294-js) one so I've just went on ahead and deleted it.

2018-05-30 00:08 UTC, dermot-hardy requested changes

2018-05-30 00:08 UTC, dermot-hardy commented on job-service-acceptance-tests/src/integration-test/java/com/hpe/caf/jobservice/acceptance/JobServiceEndToEndIT.java
> +        Thread.sleep(10000); // Add short delay to allow J1 + J2 to complete.
The sleep time has doubled?

2018-05-30 00:08 UTC, dermot-hardy commented on job-service-acceptance-tests/src/integration-test/java/com/hpe/caf/jobservice/acceptance/JobServiceEndToEndIT.java
> +        //testItemAssetIds = generateWorkerBatch();   // CAF-3677: Remove this on fix
Why have these lines been commented out?

2018-05-30 00:08 UTC, dermot-hardy commented on job-service/pom.xml
> +    <!--  <version>1.6.6</version> -->
Remove pointless comment.

2018-05-30 00:08 UTC, dermot-hardy commented on job-service/pom.xml
> -
Remove pointless whitespace change.

2018-05-30 00:08 UTC, dermot-hardy commented on pom.xml
> +
Remove pointless whitespace change.

2018-05-30 00:08 UTC, dermot-hardy commented on worker-jobtracking-container/pom.xml
> +                <rabbitmq.ctrl.port>5673</rabbitmq.ctrl.port>
Remove this change as it is clearly unrelated to this Jira.

2018-05-30 00:08 UTC, morvinshah4 commented
Created the branch SCMOD-3294-js because of Jenkins build HTTP_PROXY issue on the older Jenkins page.

2018-05-30 02:08 UTC, morvinshah4 commented
Reduced the delay to 6 seconds in the previous commit

2018-06-04 10:34 UTC, dermot-hardy requested changes

2018-06-04 10:34 UTC, dermot-hardy commented on pom.xml
> +            </dependency>
This workaround has been included in the WorkerFramework itself:
https://github.com/WorkerFramework/worker-framework/pull/68

2018-06-04 10:34 UTC, dermot-hardy commented on pom.xml
> +            </dependency>
Why have you had to add `worker-tracking-report`?  I don't see it being referenced in Job Service at all.

2018-06-04 10:34 UTC, dermot-hardy commented on pom.xml
> +            </dependency>
Why are we using different versions of `mockito-all` and `mockito-core`?

2018-06-05 00:01 UTC, morvinshah4 commented
Removed the spring-framework-bom as it is added in the worker-framework and other minor changes

2018-06-05 01:09 UTC, dermot-hardy approved these changes

2018-06-05 01:10 UTC, merged