SCMOD-3525: Updated for abstract worker changes and updated testing for tracking report task
JobService/job-service pull request #52
Opened 2018-06-13 13:36 UTC by Anthony-McGreevy

2018-06-13 16:59 UTC, dermot-hardy requested changes

2018-06-13 16:59 UTC, dermot-hardy commented on job-service-acceptance-tests/pom.xml
> +                                    <CAF_CONFIG_PATH>/config</CAF_CONFIG_PATH>
Why are `CAF_APPNAME` and `CAF_CONFIG_PATH` being added in here?

2018-06-13 16:59 UTC, dermot-hardy commented on job-service-acceptance-tests/src/integration-test/java/com/hpe/caf/jobservice/acceptance/JobServiceEndToEndIT.java
> +    private static int numTestItemsToGenerate = 2;   // CAF-3677: This cannot be set any higher than 2 otherwise the job will not reach completion. Change to final variable when fixed.
I presume this was meant to be temporary to speed up the tests?

2018-06-13 16:59 UTC, dermot-hardy commented on worker-jobtracking/pom.xml
> +
Put these up with the other compile-time dependencies rather than down here with the test dependencies.

2018-06-13 16:59 UTC, dermot-hardy commented on worker-jobtracking-container/src/main/config/cfg~caf~worker~JobTrackingWorkerConfiguration.js
> +    || (getenv("CAF_WORKER_BASE_QUEUE_NAME") || getenv("CAF_WORKER_NAME") || "worker") + "-err",
This should be tided up.

2018-06-13 16:59 UTC, dermot-hardy commented on worker-jobtracking-shared/src/main/java/com/hpe/caf/worker/jobtracking/JobReportingTransientException.java
> +public class JobReportingTransientException extends JobReportingException {
Can this class be marked `final`?

2018-06-13 16:59 UTC, dermot-hardy commented on worker-jobtracking/src/main/java/com/hpe/caf/worker/jobtracking/JobTrackingReportUpdateWorker.java
> +public class JobTrackingReportUpdateWorker extends AbstractWorker<TrackingReportTask, JobTrackingWorkerResult> {
Can the class be `final`?

2018-06-13 16:59 UTC, dermot-hardy commented on worker-jobtracking/src/main/java/com/hpe/caf/worker/jobtracking/JobTrackingWorkerUtil.java
> +public class JobTrackingWorkerUtil
This should be `final` and should have an empty private default constructor.

2018-06-14 00:23 UTC, Anthony-McGreevy commented
@dermot-hardy I have made updates to this PR to reflect your comments.

2018-06-14 04:08 UTC, dermot-hardy approved these changes

2018-06-14 04:09 UTC, merged