SCMOD-4489: null target pipe is valid (non-output worker). But empty target pipe should result in exception.
JobService/job-service pull request #75
Opened 2018-10-11 14:15 UTC by rahul-kulkarni73

2018-10-11 23:01 UTC, dermot-hardy requested changes
Also, what about [changelog.xml:48](https://github.com/JobService/job-service/blob/4841e32dd809ec642baa0cfddd64c750d73f1e7b/job-service-db/src/main/resources/v2.3.0/changelog.xml#L48) that is mentioned in the Jira.

2018-10-11 23:01 UTC, dermot-hardy commented on job-service-scheduled-executor/src/main/java/com/hpe/caf/services/job/scheduled/executor/JobTaskData.java
> +        if (targetPipe.isEmpty())
If `targetPipe==null` this will cause a `NullPointerException`.

2018-10-11 23:01 UTC, dermot-hardy commented on worker-jobtracking/src/main/java/com/hpe/caf/worker/jobtracking/JobTrackingWorkerDependency.java
> +        if (targetPipe.isEmpty())
If `targetPipe==null` this will cause a `NullPointerException`.

2018-10-14 21:55 UTC, dermot-hardy requested changes

2018-10-14 21:55 UTC, dermot-hardy commented on job-service-db/src/main/resources/v2.3.0/changelog.xml
> +                <constraints nullable="true"/>
You can't change a change set for a version that has already been released.  You have to handle this in the v2.6.0 changelog.

2018-10-18 15:12 UTC, rahul-kulkarni73 commented
Done with all requested changes. If you can review it again

2018-10-19 03:30 UTC, dermot-hardy approved these changes

2018-10-22 10:52 UTC, dermot-hardy commented
@rahul-kulkarni73 Why hasn't this been merged?

2018-10-22 10:53 UTC, dermot-hardy commented
@rahul-kulkarni73 Why hasn't this been merged?

2018-10-22 14:32 UTC, merged