SCMOD-6620: reintroduce lock in internal_process_dependent_jobs
JobService/job-service pull request #94
Opened 2019-05-28 17:10 UTC by joseph-lansdowne-micro-focus

Related to #89.  I've verified that some sort of additional locking is required, and that this is sufficient to avoid the one case that Andy was trying to resolve, by just running transactions manually.  It's different enough from the previous version of the lock that I would expect the deadlock mentioned in #89 not to be possible (though it's not obvious to me where exactly that deadlock was).

2019-05-28 21:52 UTC, dermot-hardy requested changes
> though it's not obvious to me where exactly that deadlock was

The code commented out in #89 could deadlock with the `create_job` code, if one of the new job's pre-requisites was the job actively being completed.

This code doesn't have that issue, but it does have a potential deadlock with itself, that could manifest if two jobs were completing simultaneously that were both pre-reqs of two other jobs.

Imagine:
- There is a J2 with pre-reqs of J0 and J1
- There is a J3 with pre-reqs of J0 and J1
- J0 and J1 complete near simultaneously 

There would be two simultaneously running `internal_process_dependent_jobs` calls trying to take out locks on all four rows of the `job_dependency` table.

The problem is that neither the `DELETE FROM job_dependency` statement (which will implicitly take out update locks) nor the `PERFORM NULL FROM job_dependency ... FOR KEY SHARE` statement specify an order that the locks should be taken out it.  In practice the primary key order would likely be used but this isn't specified so in theory they could deadlock with each other.

2019-05-29 09:50 UTC, joseph-lansdowne-micro-focus commented
Oh, it's actually an issue regardless of row order, isn't it?  Could deadlock if the order of those statements between the 2 transactions is delete / delete / perform / perform - since the deletes each lock only a subset of the rows.

I wasn't aware that row locks from the same statement aren't necessarily acquired atomically.  I would have expected something like that to be more explicitly spelled out - all the examples I see to do with order of locking are using multiple statements in each transaction.

2019-05-29 14:00 UTC, dermot-hardy approved these changes
> Oh, it's actually an issue regardless of row order, isn't it? Could deadlock if the order of those statements between the 2 transactions is delete / delete / perform / perform - since the deletes each lock only a subset of the rows.

Yes you're right.  The changes look good to me.

2019-05-29 14:03 UTC, dermot-hardy requested changes
On second thoughts I think there is still a problem here.

2019-05-29 14:05 UTC, dermot-hardy commented
I don't think the SHARE lock is sufficient.  I think this needs to be an UPDATE lock.

2019-05-29 14:52 UTC, joseph-lansdowne-micro-focus commented
Right, because we want the explicit locks to block each other, not just the delete, to avoid the deadlock.

2019-05-29 14:55 UTC, dermot-hardy commented
Yep

2019-05-29 15:45 UTC, dermot-hardy approved these changes

2019-05-29 16:22 UTC, merged